/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class CpuInfo */

#ifndef _Included_CpuInfo
#define _Included_CpuInfo
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
