/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class DeviceInfo */

#ifndef _Included_DeviceInfo
#define _Included_DeviceInfo
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     DeviceInfo
 * Method:    GetCpuInfo
 * Signature: ()LCpuInfo;
 */
JNIEXPORT jobject JNICALL Java_DeviceInfo_GetCpuInfo
  (JNIEnv *, jobject);

/*
 * Class:     DeviceInfo
 * Method:    GetNetInfo
 * Signature: ()LNetInfo;
 */
JNIEXPORT jobject JNICALL Java_DeviceInfo_GetNetInfo
  (JNIEnv *, jobject);

/*
 * Class:     DeviceInfo
 * Method:    GetDiskInfo
 * Signature: ()Ljava/util/ArrayList;
 */
JNIEXPORT jobject JNICALL Java_DeviceInfo_GetDiskInfo
  (JNIEnv *, jobject);

/*
 * Class:     DeviceInfo
 * Method:    GetSysInfo
 * Signature: ()LSysInfo;
 */
JNIEXPORT jobject JNICALL Java_DeviceInfo_GetSysInfo
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
