/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_vrv_cems_service_monitor_util_DeviceInfo */

#ifndef _Included_com_vrv_cems_service_monitor_util_DeviceInfo
#define _Included_com_vrv_cems_service_monitor_util_DeviceInfo
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_vrv_cems_service_monitor_util_DeviceInfo
 * Method:    GetCpuInfo
 * Signature: ()Lcom/vrv/cems/service/monitor/util/CpuInfo;
 */
JNIEXPORT jobject JNICALL Java_com_vrv_cems_service_monitor_util_DeviceInfo_GetCpuInfo
  (JNIEnv *, jobject);

/*
 * Class:     com_vrv_cems_service_monitor_util_DeviceInfo
 * Method:    GetNetInfo
 * Signature: ()Lcom/vrv/cems/service/monitor/util/NetInfo;
 */
JNIEXPORT jobject JNICALL Java_com_vrv_cems_service_monitor_util_DeviceInfo_GetNetInfo
  (JNIEnv *, jobject);

/*
 * Class:     com_vrv_cems_service_monitor_util_DeviceInfo
 * Method:    GetDiskInfo
 * Signature: ()Ljava/util/ArrayList;
 */
JNIEXPORT jobject JNICALL Java_com_vrv_cems_service_monitor_util_DeviceInfo_GetDiskInfo
  (JNIEnv *, jobject);

/*
 * Class:     com_vrv_cems_service_monitor_util_DeviceInfo
 * Method:    GetSysInfo
 * Signature: ()Lcom/vrv/cems/service/monitor/util/SysInfo;
 */
JNIEXPORT jobject JNICALL Java_com_vrv_cems_service_monitor_util_DeviceInfo_GetSysInfo
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
